trigger:
- master

pool: 'Default'

variables:
- name: npBuildStatus
  value: 'failed'
- group: nullplatform

steps:
- template: .azure/templates/nullplatform-start.yml
  
- task: NullplatformParameter@0
  inputs:
    applicationId: $(applicationId)
  name: NullplatformApplicationParameters
  displayName: "Get build parameters"

- template: .azure/templates/nullplatform-asset-build.yml

- template: .azure/templates/nullplatform-asset-push.yml

- template: .azure/templates/nullplatform-end.yml